INSERT INTO clasificacion VALUES ('01','ALIMENTOS Y BEBIDAS NO ALCOHÓLICAS');
INSERT INTO clasificacion VALUES ('011','ALIMENTOS');
INSERT INTO clasificacion VALUES ('0111','Pan y cereales');
INSERT INTO clasificacion VALUES ('01111','ARROZ');
INSERT INTO clasificacion VALUES ('01112','PAN');
INSERT INTO clasificacion VALUES ('01113','PASTA ALIMENTICIA');
INSERT INTO clasificacion VALUES ('01114','PASTELERÍA, BOLLERÍA Y MASAS COCINADAS');
INSERT INTO clasificacion VALUES ('01115','HARINAS Y CEREALES');
INSERT INTO clasificacion VALUES ('0112','Carnes');
INSERT INTO clasificacion VALUES ('01121','CARNE DE VACA');
INSERT INTO clasificacion VALUES ('01122','CARNE DE TERNERA Y AÑOJO');
INSERT INTO clasificacion VALUES ('01123','CARNE DE PORCINO');
INSERT INTO clasificacion VALUES ('01124','CARNE DE OVINO');
INSERT INTO clasificacion VALUES ('01125','CARNE DE AVE');
INSERT INTO clasificacion VALUES ('01126','CHARCUTERÍA');
INSERT INTO clasificacion VALUES ('01127','PREPARADOS DE CARNE');
INSERT INTO clasificacion VALUES ('01128','OTRAS CARNES Y CASQUERÍA');
INSERT INTO clasificacion VALUES ('0113','Pescados, crustáceos y moluscos');
INSERT INTO clasificacion VALUES ('01131','PESCADO FRESCO Y CONGELADO');
INSERT INTO clasificacion VALUES ('01132','CRUSTÁCEOS Y MOLUSCOS');
INSERT INTO clasificacion VALUES ('01133','PESCADO EN CONSERVA Y PREPARADOS');
INSERT INTO clasificacion VALUES ('0114','Productos lácteos, quesos y huevos');
INSERT INTO clasificacion VALUES ('01141','LECHE');
INSERT INTO clasificacion VALUES ('01142','OTROS PRODUCTOS LÁCTEOS');
INSERT INTO clasificacion VALUES ('01143','QUESOS');
INSERT INTO clasificacion VALUES ('01144','HUEVOS');
INSERT INTO clasificacion VALUES ('0115','Aceites y grasas');
INSERT INTO clasificacion VALUES ('01151','MANTEQUILLA Y MARGARINA');
INSERT INTO clasificacion VALUES ('01152','ACEITES');
INSERT INTO clasificacion VALUES ('0116','Frutas');
INSERT INTO clasificacion VALUES ('01161','FRUTAS FRESCAS');
INSERT INTO clasificacion VALUES ('01162','FRUTAS EN CONSERVA Y FRUTOS SECOS');
INSERT INTO clasificacion VALUES ('0117','Legumbres, hortalizas y patatas');
INSERT INTO clasificacion VALUES ('01171','LEGUMBRES Y HORTALIZAS FRESCAS');
INSERT INTO clasificacion VALUES ('01172','LEGUMBRES Y HORTALIZAS SECAS');
INSERT INTO clasificacion VALUES ('01173','LEGUMBRES Y HORTALIZAS CONGELADAS Y EN CONSERVA');
INSERT INTO clasificacion VALUES ('01174','PATATAS Y SUS PREPARADOS');
INSERT INTO clasificacion VALUES ('0118','Azúcar, chocolates y confituras');
INSERT INTO clasificacion VALUES ('01181','AZÚCAR');
INSERT INTO clasificacion VALUES ('01182','CHOCOLATES Y CONFITURAS');
INSERT INTO clasificacion VALUES ('0119','Otros productos alimenticios');
INSERT INTO clasificacion VALUES ('01191','OTROS PRODUCTOS ALIMENTICIOS');
INSERT INTO clasificacion VALUES ('012','BEBIDAS NO ALCOHÓLICAS');
INSERT INTO clasificacion VALUES ('0121','Café, cacao e infusiones');
INSERT INTO clasificacion VALUES ('01211','CAFÉ, CACAO E INFUSIONES');
INSERT INTO clasificacion VALUES ('0122','Agua mineral, refrescos y zumos');
INSERT INTO clasificacion VALUES ('01221','AGUA MINERAL, REFRESCOS Y ZUMOS');
INSERT INTO clasificacion VALUES ('02','BEBIDAS ALCOHÓLICAS Y TABACO');
INSERT INTO clasificacion VALUES ('021','BEBIDAS ALCOHÓLICAS');
INSERT INTO clasificacion VALUES ('0211','Espirituosos y licores');
INSERT INTO clasificacion VALUES ('02111','ESPIRITUOSOS Y LICORES');
INSERT INTO clasificacion VALUES ('0212','Vinos');
INSERT INTO clasificacion VALUES ('02121','VINOS');
INSERT INTO clasificacion VALUES ('0213','Cerveza');
INSERT INTO clasificacion VALUES ('02131','CERVEZA');
INSERT INTO clasificacion VALUES ('022','TABACO');
INSERT INTO clasificacion VALUES ('0221','Tabaco');
INSERT INTO clasificacion VALUES ('02211','TABACO');
INSERT INTO clasificacion VALUES ('03','VESTIDO Y CALZADO');
INSERT INTO clasificacion VALUES ('031','VESTIDO');
INSERT INTO clasificacion VALUES ('0311','Prendas de vestir');
INSERT INTO clasificacion VALUES ('03111','PRENDAS EXTERIORES DE HOMBRE');
INSERT INTO clasificacion VALUES ('03112','PRENDAS INTERIORES DE HOMBRE');
INSERT INTO clasificacion VALUES ('03113','PRENDAS EXTERIORES DE MUJER');
INSERT INTO clasificacion VALUES ('03114','PRENDAS INTERIORES DE MUJER');
INSERT INTO clasificacion VALUES ('03115','PRENDAS DE VESTIR DE NIÑO Y BEBÉ');
INSERT INTO clasificacion VALUES ('0312','Complementos y reparaciones de prendas de vestir');
INSERT INTO clasificacion VALUES ('03121','COMPLEMENTOS Y REPARACIONES DE PRENDAS DE VESTIR');
INSERT INTO clasificacion VALUES ('032','CALZADO Y SUS REPARACIONES');
INSERT INTO clasificacion VALUES ('0321','Calzado');
INSERT INTO clasificacion VALUES ('03211','CALZADO DE HOMBRE');
INSERT INTO clasificacion VALUES ('03212','CALZADO DE MUJER');
INSERT INTO clasificacion VALUES ('03213','CALZADO DE NIÑO Y BEBÉ');
INSERT INTO clasificacion VALUES ('0322','Reparación de calzado ');
INSERT INTO clasificacion VALUES ('03221','REPARACIÓN DE CALZADO');
INSERT INTO clasificacion VALUES ('04','VIVIENDA ');
INSERT INTO clasificacion VALUES ('041','ALQUILER DE VIVIENDA');
INSERT INTO clasificacion VALUES ('0411','Alquiler de vivienda');
INSERT INTO clasificacion VALUES ('04111','ALQUILER DE VIVIENDA');
INSERT INTO clasificacion VALUES ('042','CONSERVACIÓN DE LA VIVIENDA  ');
INSERT INTO clasificacion VALUES ('0421','Materiales para la conservación de la vivienda ');
INSERT INTO clasificacion VALUES ('04211','MATERIALES PARA LA CONSERVACIÓN DE LA VIVIENDA');
INSERT INTO clasificacion VALUES ('0422','Servicios para la conservación de la vivienda ');
INSERT INTO clasificacion VALUES ('04221','SERVICIOS PARA LA CONSERVACIÓN DE LA VIVIENDA');
INSERT INTO clasificacion VALUES ('043','OTROS SERVICIOS RELACIONADOS CON LA VIVIENDA ');
INSERT INTO clasificacion VALUES ('0431','Distribución de agua');
INSERT INTO clasificacion VALUES ('04311','DISTRIBUCIÓN DE AGUA');
INSERT INTO clasificacion VALUES ('0432','Recogida de basura, alcantarillado y otros servicios');
INSERT INTO clasificacion VALUES ('04321','RECOGIDA DE BASURA, ALCANTARILLADO Y OTROS SERVICIOS');
INSERT INTO clasificacion VALUES ('044','ELECTRICIDAD, GAS Y OTROS COMBUSTIBLES');
INSERT INTO clasificacion VALUES ('0441','Electricidad');
INSERT INTO clasificacion VALUES ('04411','ELECTRICIDAD');
INSERT INTO clasificacion VALUES ('0442','Gas');
INSERT INTO clasificacion VALUES ('04421','GAS');
INSERT INTO clasificacion VALUES ('0443','Otros combustibles');
INSERT INTO clasificacion VALUES ('04431','OTROS COMBUSTIBLES');
INSERT INTO clasificacion VALUES ('05','MENAJE');
INSERT INTO clasificacion VALUES ('051','MUEBLES Y OTROS ENSERES');
INSERT INTO clasificacion VALUES ('0511','Muebles y otros enseres');
INSERT INTO clasificacion VALUES ('05111','MUEBLES');
INSERT INTO clasificacion VALUES ('05112','OTROS ENSERES');
INSERT INTO clasificacion VALUES ('052','ARTÍCULOS TEXTILES PARA EL HOGAR ');
INSERT INTO clasificacion VALUES ('0521','Artículos textiles para el hogar');
INSERT INTO clasificacion VALUES ('05211','ARTÍCULOS TEXTILES PARA EL HOGAR');
INSERT INTO clasificacion VALUES ('053','ELECTRODOMÉSTICOS Y REPARACIONES');
INSERT INTO clasificacion VALUES ('0531','Electrodomésticos y reparaciones');
INSERT INTO clasificacion VALUES ('05311','FRIGORÍFICOS, LAVADORAS Y LAVAVAJILLAS');
INSERT INTO clasificacion VALUES ('05312','COCINAS Y HORNOS');
INSERT INTO clasificacion VALUES ('05313','APARATOS DE CALEFACCIÓN Y DE AIRE ACONDICIONADO');
INSERT INTO clasificacion VALUES ('05314','OTROS ELECTRODOMÉSTICOS');
INSERT INTO clasificacion VALUES ('05315','REPARACIÓN DE ELECTRODOMÉSTICOS');
INSERT INTO clasificacion VALUES ('054','UTENSILIOS DE COCINA Y MENAJE');
INSERT INTO clasificacion VALUES ('0541','Utensilios de cocina y menaje');
INSERT INTO clasificacion VALUES ('05411','CRISTALERIA, VAJILLA Y CUBERTERÍA');
INSERT INTO clasificacion VALUES ('05412','OTROS UTENSILIOS DE COCINA Y MENAJE');
INSERT INTO clasificacion VALUES ('055','HERRAMIENTAS Y ACCESORIOS PARA CASA Y JARDIN');
INSERT INTO clasificacion VALUES ('0551','Herramientas y accesorios para casa y jardín');
INSERT INTO clasificacion VALUES ('05511','HERRAMIENTAS Y ACCESORIOS PARA CASA Y JARDIN');
INSERT INTO clasificacion VALUES ('056','OTROS BIENES Y SERVICIOS PARA EL HOGAR');
INSERT INTO clasificacion VALUES ('0561','Artículos no duraderos para el hogar');
INSERT INTO clasificacion VALUES ('05611','ARTÍCULOS DE LIMPIEZA PARA EL HOGAR');
INSERT INTO clasificacion VALUES ('05612','OTROS ARTÍCULOS NO DURADEROS PARA EL HOGAR');
INSERT INTO clasificacion VALUES ('0562','Servicio doméstico y otros servicios para el hogar');
INSERT INTO clasificacion VALUES ('05621','SERVICIO DOMÉSTICO Y OTROS SERVICIOS PARA EL HOGAR');
INSERT INTO clasificacion VALUES ('06','MEDICINA ');
INSERT INTO clasificacion VALUES ('061','MEDICAMENTOS, OTROS PRODUCTOS FARMACÉUTICOS Y MATERIAL TERAPÉUTICO');
INSERT INTO clasificacion VALUES ('0611','Medicamentos, otros productos farmacéuticos y material terapéutico');
INSERT INTO clasificacion VALUES ('06111','MEDICAMENTOS Y OTROS PRODUCTOS FARMACÉUTICOS');
INSERT INTO clasificacion VALUES ('06112','MATERIAL TERAPÉUTICO');
INSERT INTO clasificacion VALUES ('062','SERVICIOS MÉDICOS, DENTALES Y PARAMÉDICOS NO HOSPITALARIOS');
INSERT INTO clasificacion VALUES ('0621','Servicios médicos y paramédicos no hospitalarios');
INSERT INTO clasificacion VALUES ('06211','SERVICIOS MÉDICOS Y PARAMÉDICOS NO HOSPITALARIOS');
INSERT INTO clasificacion VALUES ('0622','Servicios dentales');
INSERT INTO clasificacion VALUES ('06221','SERVICIOS DENTALES');
INSERT INTO clasificacion VALUES ('063','SERVICIOS HOSPITALARIOS');
INSERT INTO clasificacion VALUES ('0631','Servicios hospitalarios');
INSERT INTO clasificacion VALUES ('06311','SERVICIOS HOSPITALARIOS');
INSERT INTO clasificacion VALUES ('07','TRANSPORTE');
INSERT INTO clasificacion VALUES ('071','VEHÍCULOS');
INSERT INTO clasificacion VALUES ('0711','Automóviles');
INSERT INTO clasificacion VALUES ('07111','AUTOMÓVILES');
INSERT INTO clasificacion VALUES ('0712','Otros vehículos');
INSERT INTO clasificacion VALUES ('07121','OTROS VEHÍCULOS');
INSERT INTO clasificacion VALUES ('072','BIENES Y SERVICIOS RELATIVOS A LOS VEHÍCULOS');
INSERT INTO clasificacion VALUES ('0721','Repuestos y accesorios de mantenimiento');
INSERT INTO clasificacion VALUES ('07211','REPUESTOS Y ACCESORIOS DE MANTENIMIENTO');
INSERT INTO clasificacion VALUES ('0722','Carburantes y lubricantes');
INSERT INTO clasificacion VALUES ('07221','CARBURANTES Y LUBRICANTES');
INSERT INTO clasificacion VALUES ('0723','Servicios de mantenimiento y reparaciones');
INSERT INTO clasificacion VALUES ('07231','SERVICIOS DE MANTENIMIENTO Y REPARACIONES');
INSERT INTO clasificacion VALUES ('0724','Otros servicios relativos a los vehículos');
INSERT INTO clasificacion VALUES ('07241','OTROS SERVICIOS RELATIVOS A LOS VEHÍCULOS');
INSERT INTO clasificacion VALUES ('073','SERVICIOS DE TRANSPORTE');
INSERT INTO clasificacion VALUES ('0731','Transporte por ferrocarril');
INSERT INTO clasificacion VALUES ('07311','TRANSPORTE POR FERROCARRIL');
INSERT INTO clasificacion VALUES ('0732','Transporte por carretera');
INSERT INTO clasificacion VALUES ('07321','TRANSPORTE POR CARRETERA');
INSERT INTO clasificacion VALUES ('0733','Transporte aéreo');
INSERT INTO clasificacion VALUES ('07331','TRANSPORTE AÉREO');
INSERT INTO clasificacion VALUES ('0734','Otros servicios de transporte');
INSERT INTO clasificacion VALUES ('07341','OTROS SERVICIOS DE TRANSPORTE');
INSERT INTO clasificacion VALUES ('08','COMUNICACIONES');
INSERT INTO clasificacion VALUES ('081','COMUNICACIONES');
INSERT INTO clasificacion VALUES ('0811','Servicios postales');
INSERT INTO clasificacion VALUES ('08111','SERVICIOS POSTALES');
INSERT INTO clasificacion VALUES ('0812','Equipos y servicios telefónicos');
INSERT INTO clasificacion VALUES ('08121','EQUIPOS Y SERVICIOS TELEFÓNICOS');
INSERT INTO clasificacion VALUES ('09','OCIO Y CULTURA');
INSERT INTO clasificacion VALUES ('091','EQUIPOS Y SOPORTES AUDIOVISUALES, FOTOGRÁFICOS E INFORMÁTICOS');
INSERT INTO clasificacion VALUES ('0911','Equipos de imagen y sonido ');
INSERT INTO clasificacion VALUES ('09111','EQUIPOS DE IMAGEN Y SONIDO');
INSERT INTO clasificacion VALUES ('0912','Equipos fotográficos y cinematográficos');
INSERT INTO clasificacion VALUES ('09121','EQUIPOS FOTOGRÁFICOS Y CINEMATOGRÁFICOS');
INSERT INTO clasificacion VALUES ('0913','Equipos informáticos');
INSERT INTO clasificacion VALUES ('09131','EQUIPOS INFORMÁTICOS');
INSERT INTO clasificacion VALUES ('0914','Soporte para el registro de imagen y sonido');
INSERT INTO clasificacion VALUES ('09141','SOPORTE PARA EL REGISTRO DE IMAGEN Y SONIDO');
INSERT INTO clasificacion VALUES ('0915','Reparación de equipos audiovisuales, fotográficos e informáticos');
INSERT INTO clasificacion VALUES ('09151','REPARACIÓN DE EQUIPOS AUDIOVISUALES, FOTOGRÁFICOS E INFORMÁTICOS');
INSERT INTO clasificacion VALUES ('092','ARTÍCULOS RECREATIVOS Y DEPORTIVOS; FLORISTERÍA Y MASCOTAS');
INSERT INTO clasificacion VALUES ('0921','Artículos recreativos y deportivos');
INSERT INTO clasificacion VALUES ('09211','JUEGOS Y JUGUETES');
INSERT INTO clasificacion VALUES ('09212','OTROS ARTÍCULOS RECREATIVOS Y DEPORTIVOS');
INSERT INTO clasificacion VALUES ('0922','Floristería y mascotas');
INSERT INTO clasificacion VALUES ('09221','FLORISTERÍA Y MASCOTAS');
INSERT INTO clasificacion VALUES ('093','SERVICIOS RECREATIVOS, DEPORTIVOS Y CULTURALES');
INSERT INTO clasificacion VALUES ('0931','Servicios recreativos y deportivos');
INSERT INTO clasificacion VALUES ('09311','SERVICIOS RECREATIVOS Y DEPORTIVOS');
INSERT INTO clasificacion VALUES ('0932','Servicios culturales');
INSERT INTO clasificacion VALUES ('09321','SERVICIOS CULTURALES');
INSERT INTO clasificacion VALUES ('094','LIBROS, PRENSA Y PAPELERÍA');
INSERT INTO clasificacion VALUES ('0941','Libros');
INSERT INTO clasificacion VALUES ('09411','LIBROS');
INSERT INTO clasificacion VALUES ('0942','Prensa y revistas');
INSERT INTO clasificacion VALUES ('09421','PRENSA Y REVISTAS');
INSERT INTO clasificacion VALUES ('0943','Material de papelería');
INSERT INTO clasificacion VALUES ('09431','MATERIAL DE PAPELERÍA');
INSERT INTO clasificacion VALUES ('095','VIAJE ORGANIZADO');
INSERT INTO clasificacion VALUES ('0951','Viaje organizado');
INSERT INTO clasificacion VALUES ('09511','VIAJE ORGANIZADO');
INSERT INTO clasificacion VALUES ('10','ENSEÑANZA');
INSERT INTO clasificacion VALUES ('101','ENSEÑANZA');
INSERT INTO clasificacion VALUES ('1011','Educación infantil y primaria');
INSERT INTO clasificacion VALUES ('10111','EDUCACIÓN INFANTIL Y PRIMARIA');
INSERT INTO clasificacion VALUES ('1012','Enseñanza secundaria');
INSERT INTO clasificacion VALUES ('10121','ENSEÑANZA SECUNDARIA');
INSERT INTO clasificacion VALUES ('1013','Enseñanza superior');
INSERT INTO clasificacion VALUES ('10131','ENSEÑANZA SUPERIOR');
INSERT INTO clasificacion VALUES ('1014','Otras enseñanzas');
INSERT INTO clasificacion VALUES ('10141','OTRAS ENSEÑANZAS');
INSERT INTO clasificacion VALUES ('11','HOTELES, CAFÉS Y RESTAURANTES');
INSERT INTO clasificacion VALUES ('111','RESTAURANTES, BARES Y CAFETERÍAS');
INSERT INTO clasificacion VALUES ('1111','Restaurantes, bares y cafeterías');
INSERT INTO clasificacion VALUES ('11111','RESTAURANTES, BARES Y CAFETERÍAS');
INSERT INTO clasificacion VALUES ('112','HOTELES Y OTROS ALOJAMIENTOS ');
INSERT INTO clasificacion VALUES ('1121','Hoteles y otros alojamientos');
INSERT INTO clasificacion VALUES ('11211','HOTELES Y OTROS ALOJAMIENTOS');
INSERT INTO clasificacion VALUES ('12','OTROS BIENES Y SERVICIOS');
INSERT INTO clasificacion VALUES ('121','BIENES Y SERVICIOS PARA EL CUIDADO PERSONAL');
INSERT INTO clasificacion VALUES ('1211','Servicios para el cuidado personal');
INSERT INTO clasificacion VALUES ('12111','SERVICIOS PARA EL CUIDADO PERSONAL');
INSERT INTO clasificacion VALUES ('1212','Artículos para el cuidado personal');
INSERT INTO clasificacion VALUES ('12121','ARTÍCULOS PARA EL CUIDADO PERSONAL');
INSERT INTO clasificacion VALUES ('122','ARTÍCULOS DE USO PERSONAL');
INSERT INTO clasificacion VALUES ('1221','Joyería, bisutería y relojería');
INSERT INTO clasificacion VALUES ('12211','JOYERÍA, BISUTERÍA Y RELOJERÍA');
INSERT INTO clasificacion VALUES ('1222','Otros artículos de uso personal');
INSERT INTO clasificacion VALUES ('12221','OTROS ARTÍCULOS DE USO PERSONAL');
INSERT INTO clasificacion VALUES ('123','SERVICIOS SOCIALES');
INSERT INTO clasificacion VALUES ('1231','Servicios sociales');
INSERT INTO clasificacion VALUES ('12311','SERVICIOS SOCIALES');
INSERT INTO clasificacion VALUES ('124','SEGUROS');
INSERT INTO clasificacion VALUES ('1241','Seguros para la vivienda');
INSERT INTO clasificacion VALUES ('12411','SEGUROS PARA LA VIVIENDA');
INSERT INTO clasificacion VALUES ('1242','Seguros médicos');
INSERT INTO clasificacion VALUES ('12421','SEGUROS MÉDICOS');
INSERT INTO clasificacion VALUES ('1243','Seguros de automóvil');
INSERT INTO clasificacion VALUES ('12431','SEGUROS DE AUTOMÓVIL');
INSERT INTO clasificacion VALUES ('1244','Otros seguros');
INSERT INTO clasificacion VALUES ('12441','OTROS SEGUROS');
INSERT INTO clasificacion VALUES ('125','SERVICIOS FINANCIEROS');
INSERT INTO clasificacion VALUES ('1251','Servicios financieros');
INSERT INTO clasificacion VALUES ('12511','SERVICIOS FINANCIEROS');
INSERT INTO clasificacion VALUES ('126','OTROS SERVICIOS ');
INSERT INTO clasificacion VALUES ('1261','Otros servicios');
INSERT INTO clasificacion VALUES ('12611','OTROS SERVICIOS');
